export const FAMILY_TASK_ROUTES = {
  root: "/family-tasks",
  today: "/family-tasks/today",
  calendar: "/family-tasks/calendar",
  calendarEventNew: "/family-tasks/calendar/events/new",
  chores: "/family-tasks/chores",
  choresNew: "/family-tasks/chores/new",
  routines: "/family-tasks/routines",
  routinesNew: "/family-tasks/routines/new",
  rewards: "/family-tasks/rewards",
  rewardsNew: "/family-tasks/rewards/new",
  rewardsRedemptions: "/family-tasks/rewards/redemptions",
  lists: "/family-tasks/lists",
  profiles: "/family-tasks/profiles",
  invitations: "/family-tasks/invitations",
  devices: "/family-tasks/devices",
  devicesNew: "/family-tasks/devices/new",
  display: "/family-tasks/display",
  approvals: "/family-tasks/approvals",
  settings: "/family-tasks/settings",
} as const;
